### ISSUE TITLE
Using a pre-trained model

### ISSUE THREAD

**Issue by adhocmaster** [dotchen/LAV#14]
Hi there,

I would like to test the pre-trained model against pedestrian models that I have been developing. I see there is a weight folder but still not sure how to create an agent and load the weights. Can you guide me?

**Comment by dotchen** [comment]
Thank you for your interest in our project.

Please follow the instructions [here](https://github.com/dotchen/LAV#evaluation) on how to directly run an agent with pre-trained model weights. 
Please make sure to have installed `git-lfs` before cloning the repo.

**Comment by adhocmaster** [comment]
Thanks for the prompt reponse.

**Comment by varunjammula** [comment]
Hi @dotchen, when are you planning on releasing the Leaderboard weights for model evaluation? Thanks in advance.

**Comment by dotchen** [comment]
I am currently a bit busy with an internship but I will try to find a weekend to refactor and release it.

**Comment by ricokoff** [comment]
Hi @dotchen,

Are there any updates on the leaderboard weights?

**Comment by xolovezarii** [comment]
> Thank you for your interest in our project.
> 
> Please follow the instructions [here](https://github.com/dotchen/LAV#evaluation) on how to directly run an agent with pre-trained model weights. Please make sure to have installed `git-lfs` before cloning the repo.

Hi @dotchen 
I followed what said in the repo but  still don't know what should I do with "wights" folder!?
I run the project and it' output is like this:


 Running the route
======[Agent] Wallclock_time = 2024-03-10 08:13:24.232159 / 0.0 / Sim_time = 0.05000000074505806 / 50.00000074505806x
======[Agent] Wallclock_time = 2024-03-10 08:13:25.015090 / 0.782931 / Sim_time = 0.10000000149011612 / 0.12756224908839695x

Stopping the route, the agent has crashed:
> Not compiled with CUDA support

Traceback (most recent call last):
  File "/home/missakhbariun/LAV/leaderboard/leaderboard/scenarios/scenario_manager.py", line 152, in _tick_scenario
    ego_action = self._agent()
  File "/home/missakhbariun/LAV/leaderboard/leaderboard/autoagents/agent_wrapper.py", line 75, in __call__
    return self._agent()
  File "/home/missakhbariun/LAV/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 115, in __call__
    control = self.run_step(input_data, timestamp)
  File "/home/missakhbariun/miniconda3/envs/LAV-env/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/missakhbariun/LAV/team_code_v2/lav_agent.py", line 318, in run_step
    pred_bev = self.lidar_model([lidar_points], [len(lidar_points)])
  File "/home/missakhbariun/miniconda3/envs/LAV-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/missakhbariun/LAV/team_code_v2/models/lidar.py", line 37, in forward
    features = self.point_pillar_net(lidars, num_points)
  File "/home/missakhbariun/miniconda3/envs/LAV-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/missakhbariun/LAV/team_code_v2/models/point_pillar.py", line 114, in forward
    features = self.point_net(decorated_points, inverse_indices)
  File "/home/missakhbariun/miniconda3/envs/LAV-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/missakhbariun/LAV/team_code_v2/models/point_pillar.py", line 33, in forward
    feat_max = scatter_max(feat, inverse_indices, dim=0)[0]
  File "/home/missakhbariun/miniconda3/envs/LAV-env/lib/python3.7/site-packages/torch_scatter/scatter.py", line 72, in scatter_max
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
  File "/home/missakhbariun/miniconda3/envs/LAV-env/lib/python3.7/site-packages/torch/_ops.py", line 442, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Not compiled with CUDA support

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/missakhbariun/LAV/leaderboard/leaderboard_evaluator.py", line 352, in _load_and_run_scenario
    self.manager.run_scenario()
  File "/home/missakhbariun/LAV/leaderboard/leaderboard/scenarios/scenario_manager.py", line 136, in run_scenario
    self._tick_scenario(timestamp)
  File "/home/missakhbariun/LAV/leaderboard/leaderboard/scenarios/scenario_manager.py", line 159, in _tick_scenario
    raise AgentError(e)
leaderboard.autoagents.agent_wrapper.AgentError: Not compiled with CUDA support
> Stopping the route

========= Results of RouteScenario_25 (repetition 0) ------ FAILURE =========

╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2024-03-07 22:05:05 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2024-03-07 22:05:07 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 1.97s               │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 0.1s                │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.051               │
╘═════════════════════════════════╧═════════════════════╛

╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ FAILURE │ 0.0 %   │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ SUCCESS │ 0 %     │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ SUCCESS │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ SUCCESS │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningStopTest       │ SUCCESS │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ SUCCESS │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ SUCCESS │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ SUCCESS │         │
╘═══════════════════════╧═════════╧═════════╛

> Registering the route statistics
> Registering the global statistics


It looks like it did not use the pretrained wights and models.

what should I do???
I would be so thankful if you guys help me, too.@varunjammula @adhocmaster @ricokoff @philkr
