### ISSUE TITLE
No module named 'models.lidar'

### ISSUE THREAD

**Issue by bobd988** [dotchen/LAV#7]
Hi,

I got error when I ran  ROUTES= ./leaderboard/scripts/run_evaluation.sh in LAV-env conda environment.
Here is the error message. I am running Ubuntu 18.04 with the installation steps followed. 
Traceback (most recent call last):
  File "/home/demo/Public/LAV/leaderboard/leaderboard/leaderboard_evaluator.py", line 457, in main
    leaderboard_evaluator = LeaderboardEvaluator(arguments, statistics_manager)
  File "/home/demo/Public/LAV/leaderboard/leaderboard/leaderboard_evaluator.py", line 91, in __init__
    self.module_agent = importlib.import_module(module_name)
  File "/home/demo/anaconda3/envs/LAV-env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/demo/Public/LAV/team_code/lav_agent.py", line 15, in <module>
    from models.lidar import LiDARModel
ModuleNotFoundError: No module named 'models.lidar'

How can I fix this?  Thanks.

**Comment by dotchen** [comment]
Hello,

Can you do a `ls -alth team_code/models` in the root repo directory and make sure the symbolic links are properly setup?
If it is correct it should show you something like this:

```bash
config.yaml -> ../config.yaml
models -> ../lav/models
point_painting.py -> ../lav/utils/point_painting.py
```

**Comment by dotchen** [comment]
Hi @bobd988, I am curious if you still having trouble with this? I did it again on my end and it work out-of-box, so if there is a setup-specific issue I would like to pin it down. thanks!

**Comment by bobd988** [comment]
Sorry for late reply. I guess it is my env issue as I changed a different PC and this issue not happen again.  However I got another issue " Could not set up the required agent:
> <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)".  I solved this by changing all https to http in all files and then program was ok to run.  Hope this help anyone who met same issue.

**Comment by Watson52** [comment]
>     from models.lidar import LiDARModel ModuleNotFoundError: No module named 'models'

Hi, @dotchen .I just meet the same error too. And when I do the command `ls -alth team_code/` it shows like this:

> drwxrwxrwx  2 ser  4.0K 30 13:17 __ pycache __
drwxrwxrwx  3 ser  4.0K   30 13:13 .
-rwxrwxrwx  1 ser 13K   30 13:13 lav_agent.py
drwxrwxrwx 10 ser 4.0K   30 12:04 ..
-rwxrwxrwx  1 ser    0   19 00:18 config.yaml
-rwxrwxrwx  1 ser    0   19 00:18 models
-rwxrwxrwx  1 ser  760    6 06:57 pid.py
-rwxrwxrwx  1 ser 1.6K    6 06:57 planner.py
-rwxrwxrwx  1 ser 2.0K    6 06:57 point_painting.py
-rwxrwxrwx  1 ser 2.5K    6 06:57 waypointer.py

Could you give me some suggestions?
